#!/bin/bash
export CVSROOT=:ext:ist178865@sigma.ist.utl.pt:/afs/ist.utl.pt/groups/leic-co/co16/cvs/103
export CVS_RSH=ssh
export M2_HOME=/opt/apache-maven-3.3.9
export PATH=$PATH:$M2_HOME/bin

#export JAVA_HOME=/usr/lib64/jdk1.8.0_72
export PATH=$PATH:$JAVA_HOME/bin

#export TORRENT_ADD=utilizador@acer:/media/utilizador/Seagate\ Expansion\ Drive/Acer\ Downloads/Add\ Torrents/
