#!/bin/bash

# Colors
echo -e "Default \e[30mBlack\e[0m"
echo -e "Default \e[31mRed\e[0m"
echo -e "Default \e[32mGreen\e[0m"
echo -e "Default \e[33mYellow\e[0m"
echo -e "Default \e[34mBlue\e[0m"
echo -e "Default \e[35mMagenta\e[0m"
echo -e "Default \e[36mCyan\e[0m"
echo -e "Default \e[37mLight gray\e[0m"
echo -e "Default \e[90mDark gray\e[0m"
echo -e "Default \e[91mLight red\e[0m"
echo -e "Default \e[92mLight green\e[0m"
echo -e "Default \e[93mLight yellow\e[0m"
echo -e "Default \e[94mLight blue\e[0m"
echo -e "Default \e[95mLight magenta\e[0m"
echo -e "Default \e[96mLight cyan\e[0m"
echo -e "Default \e[39mDefault\e[0m"
echo -e "Default \e[97mWhite\e[0m"
DotFilesPath=$(pwd)

echo "Consider this -> https://github.com/dim-an/cod"

cd ~
rm .bashrc
rm .bash_profile
rm .inputrc

rm .zshrc

rm .exports
rm .alias
rm .shellrc

ln -s $DotFilesPath/inputrc .inputrc
ln -s $DotFilesPath/zshrc .zshrc
ln -s $DotFilesPath/bashrc .bashrc
ln -s $DotFilesPath/bash_profile .bash_profile

ln -s $DotFilesPath/exports .exports
ln -s $DotFilesPath/alias .alias
ln -s $DotFilesPath/shellrc .shellrc
ln -s $DotFilesPath/dracula.zsh-theme ~/.oh-my-zsh/themes/dracula.zsh-theme

ln -s $DotFilesPath/dev_env.d .dev_env.d 

echo "Create symbolic link for git completion:"
echo "(cd /usr/local/etc/bash_completion.d/ ; ln -s $DotFilesPath/files/git-completion.bash)"

echo
echo

echo "Have git-prompt in PATH"
echo "cp $DotFilesPath/files/git-prompt.sh ~/bin"
