#!/bin/bash
# export M2_HOME=/opt/apache-maven-3.3.9
# export PATH=$PATH:$M2_HOME/bin
#export JAVA_HOME=/usr/lib64/jdk1.8.0_72
# export JAVA_HOME=/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0
# export PATH=$PATH:$JAVA_HOME/bin
# export PATH=/opt/apache-maven-3.3.9/bin:$PATH
# export PATH=/opt/terraform:$PATH




# export TALKDESK=$HOME/talkdesk
